export const UserData = [
    {
        id: 1,
        name: "Andi Saputra",
        email: "andi.saputra@example.com",
        role: "PAW01",
        isActive: false,
        createdAt: "2024-10-01T08:30:00Z",
    },
    {
        id: 2,
        name: "Budi Santoso",
        email: "budi.santoso@example.com",
        role: "PAW02",
        isActive: false,
        createdAt: "2024-11-15T10:00:00Z",
    },
    {
        id: 3,
        name: "Citra Dewi",
        email: "citra.dewi@example.com",
        role: "PAW01",
        isActive: false,
        createdAt: "2024-09-20T13:45:00Z",
    },
    {
        id: 4,
        name: "Dedi Firmansyah",
        email: "dedi.firmansyah@example.com",
        role: "PAW02",
        isActive: false,
        createdAt: "2025-01-05T09:20:00Z",
    },
    {
        id: 5,
        name: "Eka Yuliani",
        email: "eka.yuliani@example.com",
        role: "PAW02",
        isActive: false,
        createdAt: "2024-08-12T16:10:00Z",
    },
    {
        id: 6,
        name: "Fajar Maulana",
        email: "fajar.maulana@example.com",
        role: "PAW01",
        isActive: false,
        createdAt: "2024-10-22T14:30:00Z",
    },
    {
        id: 7,
        name: "Gita Prameswari",
        email: "gita.prameswari@example.com",
        role: "PAW02",
        isActive: false,
        createdAt: "2024-12-01T09:00:00Z",
    },
    {
        id: 8,
        name: "Hendra Gunawan",
        email: "hendra.gunawan@example.com",
        role: "PAW01",
        isActive: false,
        createdAt: "2025-01-10T11:15:00Z",
    },
    {
      id: 9,
      name: "Intan Lestari",
      email: "intan.lestari@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-09-28T12:20:00Z",
    },
    {
      id: 10,
      name: "Joko Sutrisno",
      email: "joko.sutrisno@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-10-19T07:55:00Z",
    },
    {
      id: 11,
      name: "Kiki Amalia",
      email: "kiki.amalia@example.com",
      role: "PAW01",
      isActive: false,
      createdAt: "2024-11-03T10:10:00Z",
    },
    {
      id: 12,
      name: "Lukman Hakim",
      email: "lukman.hakim@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-09-05T13:40:00Z",
    },
    {
      id: 13,
      name: "Maya Sari",
      email: "maya.sari@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-12-15T15:25:00Z",
    },
    {
      id: 14,
      name: "Nurul Huda",
      email: "nurul.huda@example.com",
      role: "PAW01",
      isActive: false,
      createdAt: "2024-10-30T17:05:00Z",
    },
    {
      id: 15,
      name: "Oki Setiawan",
      email: "oki.setiawan@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-11-25T08:45:00Z",
    },
    {
      id: 16,
      name: "Putri Ayu",
      email: "putri.ayu@example.com",
      role: "PAW01",
      isActive: false,
      createdAt: "2024-08-22T18:30:00Z",
    },
    {
      id: 17,
      name: "Rudi Hartono",
      email: "rudi.hartono@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2024-09-12T09:35:00Z",
    },
    {
      id: 18,
      name: "Sari Melati",
      email: "sari.melati@example.com",
      role: "PAW01",
      isActive: false,
      createdAt: "2024-12-05T14:50:00Z",
    },
    {
      id: 19,
      name: "Teguh Wibowo",
      email: "teguh.wibowo@example.com",
      role: "PAW02",
      isActive: false,
      createdAt: "2025-01-02T16:20:00Z",
    },
    {
      id: 20,
      name: "Umi Kalsum",
      email: "umi.kalsum@example.com",
      role: "PAW01",
      isActive: false,
      createdAt: "2024-10-08T07:00:00Z",
    },
  ];
  